"use client";

import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";
import { assetUrl, colorFields, colorLabels, ratios } from "@/lib/studio-types";
import type { HomeDraft, MediaDraft, ProjectDraft, StudioAsset, StudioProject, StudioState } from "@/lib/studio-types";

async function api<T>(body?: unknown): Promise<T> {
  const response = await fetch("/api/studio", body === undefined ? { cache: "no-store" } : body instanceof FormData
    ? { method: "POST", body }
    : { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const value = await response.json();
  if (!response.ok) throw new Error(value.error ?? "Unable to complete this action.");
  return value;
}
function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) {
  return <label className="studio-field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>;
}
function Colors({ data, prefix = "", change }: { data: Record<string, unknown>; prefix?: string; change: (key: string, value: string) => void }) {
  return <div className="studio-fields">{colorFields.map((field, index) => {
    const key = prefix ? prefix + field[0].toUpperCase() + field.slice(1) : field;
    const value = String(data[key] ?? "#000000");
    return <Field label={colorLabels[index]} key={key}><div className="studio-color">
      <span className="studio-swatch" style={{ background: /^#[\da-f]{3,8}$/i.test(value) ? value : "transparent" }} />
      <input value={value} onChange={(event) => change(key, event.target.value)} spellCheck={false} />
    </div></Field>;
  })}</div>;
}
function Thumbnail({ id, src, alt = "", type = "image" }: { id: string; src?: string; alt?: string; type?: string }) {
  if (!src) return <div className="studio-empty-image">No cover yet</div>;
  if (type === "video") return <video src={assetUrl(id, src)} controls preload="metadata" aria-label={alt || "Video preview"} />;
  // These previews are generated by the local editor endpoint.
  // eslint-disable-next-line @next/next/no-img-element
  return <img src={assetUrl(id, src)} alt={alt} loading="lazy" />;
}

export function Studio() {
  const [state, setState] = useState<StudioState | null>(null);
  const [selected, setSelected] = useState<string>("overview");
  const [project, setProject] = useState<StudioProject | null>(null);
  const [home, setHome] = useState<StudioState["home"] | null>(null);
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [query, setQuery] = useState("");
  const [creating, setCreating] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newSlug, setNewSlug] = useState("");
  const [slugEdited, setSlugEdited] = useState(false);
  const [assetChoice, setAssetChoice] = useState("");
  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => { api<StudioState>().then(setState).catch((e) => setError(e.message)); }, []);
  useEffect(() => {
    if (creating) dialogRef.current?.showModal();
  }, [creating]);
  useEffect(() => {
    const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } };
    window.addEventListener("beforeunload", warn);
    return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);

  function switchTo(id: string, source = state) {
    if (busy || !source) return;
    if (dirty && !window.confirm("Discard unsaved changes and switch pages?")) return;
    setSelected(id); setDirty(false); setError(""); setNotice(""); setAssetChoice("");
    setProject(id.startsWith("project:") ? structuredClone(source.projects.find((p) => p.id === id.slice(8))!) : null);
    setHome(id === "home" ? structuredClone(source.home) : null);
  }
  function changeProject(key: string, value: unknown) {
    setProject((current) => current ? { ...current, data: { ...current.data, [key]: value } as ProjectDraft } : null);
    setDirty(true); setNotice("");
  }
  function changeHome(key: string, value: unknown) {
    setHome((current) => current ? { ...current, data: { ...current.data, [key]: value } as HomeDraft } : null);
    setDirty(true); setNotice("");
  }
  function changeMedia(index: number, key: string, value: string) {
    if (!project) return;
    changeProject("content", project.data.content.map((item, i) => i === index ? { ...item, [key]: value } : item));
  }
  function moveMedia(index: number, direction: number) {
    if (!project) return;
    const content = [...project.data.content];
    [content[index], content[index + direction]] = [content[index + direction], content[index]];
    changeProject("content", content);
  }
  function addAsset(asset: StudioAsset) {
    if (!project) return;
    const item: MediaDraft = { type: asset.type, src: asset.src, alt: "", aspectRatio: "Default", captionPosition: "bottom" };
    changeProject("content", [...project.data.content, item]); setAssetChoice("");
  }
  async function save() {
    setBusy(true); setError(""); setNotice("");
    try {
      if (project) {
        const saved = await api<StudioProject>({ action: "project", id: project.id, revision: project.revision, data: project.data });
        setProject(saved);
        setState((current) => current ? { ...current, projects: current.projects.map((p) => p.id === saved.id ? saved : p).sort((a, b) => a.data.homeOrder - b.data.homeOrder || a.data.title.localeCompare(b.data.title)) } : null);
      } else if (home) {
        const saved = await api<StudioState["home"]>({ action: "home", revision: home.revision, data: home.data });
        setHome(saved); setState((current) => current ? { ...current, home: saved } : null);
      }
      setDirty(false); setNotice("Saved to Markdown. Refresh the portfolio to see your changes.");
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function reload() {
    if (dirty && !window.confirm("Reload from disk and discard your unsaved changes?")) return;
    setBusy(true); setError("");
    try {
      const next = await api<StudioState>(); setState(next);
      setProject(selected.startsWith("project:") ? structuredClone(next.projects.find((p) => p.id === selected.slice(8)) ?? null) : null);
      setHome(selected === "home" ? structuredClone(next.home) : null); setDirty(false); setNotice("Loaded the latest files.");
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function create() {
    setBusy(true); setError("");
    try {
      const created = await api<StudioProject>({ action: "create", title: newTitle, slug: newSlug });
      setState((current) => current ? { ...current, projects: [...current.projects, created] } : null);
      setSelected(`project:${created.id}`); setProject(created); setHome(null); setDirty(false); setCreating(false);
      setNewTitle(""); setNewSlug(""); setSlugEdited(false); setNotice("Draft created. Add a cover and media, then publish when ready.");
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function upload(files: FileList | null, cover = false) {
    if (!files?.length || !project) return;
    setBusy(true); setError(""); setNotice("");
    const added: StudioAsset[] = [];
    try {
      for (const file of Array.from(files)) {
        setNotice(`Uploading ${file.name}…`);
        const form = new FormData(); form.set("project", project.id); form.set("file", file);
        added.push(await api<StudioAsset>(form));
      }
      setNotice("Uploaded. Save changes to update the page.");
    } catch (e) { setError((e as Error).message); setNotice(""); }
    finally {
      if (added.length) {
        setState((current) => current ? { ...current, projects: current.projects.map((p) => p.id === project.id ? { ...p, assets: [...p.assets, ...added] } : p) } : null);
        setProject((current) => current ? { ...current, assets: [...current.assets, ...added], data: {
          ...current.data,
          ...(cover ? { cover: added[0].src } : { content: [...current.data.content, ...added.map((asset) => ({ type: asset.type, src: asset.src, alt: "", aspectRatio: "Default", captionPosition: "bottom" }))] }),
        } } : null);
        setDirty(true);
      }
      setBusy(false);
    }
  }
  function newProject() {
    if (dirty && !window.confirm("Discard unsaved changes and create a new project?")) return;
    setError(""); setCreating(true);
  }

  const filtered = (state?.projects ?? []).filter((p) => `${p.data.title} ${p.data.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const title = project?.data.title ?? (home ? "Homepage" : "Your projects");
  return <main className="studio">
    <aside className="studio-sidebar">
      <a className="studio-brand" href="/studio">Portfolio <span>Studio<span className="studio-star">*</span></span></a>
      <p className="studio-local"><span /> Local workspace</p>
      <nav aria-label="Studio navigation">
        <button className={selected === "overview" ? "is-selected" : ""} onClick={() => switchTo("overview")} disabled={busy}>Projects <span>{state?.projects.length ?? "—"}</span></button>
        <button className={selected === "home" ? "is-selected" : ""} onClick={() => switchTo("home")} disabled={busy}>Homepage <span>↗</span></button>
      </nav>
      <div className="studio-sidebar-projects"><p className="studio-eyebrow">Quick access</p>{state?.projects.map((p) => <button key={p.id} onClick={() => switchTo(`project:${p.id}`)} className={project?.id === p.id ? "is-selected" : ""} disabled={busy}><span>{p.data.title}</span><small>{p.data.published ? "" : "Draft"}</small></button>)}</div>
      <div className="studio-sidebar-footer"><p>Your content, in your files.</p><small>Markdown + original media</small><a href="/" target="_blank" rel="noreferrer">Open portfolio ↗</a></div>
    </aside>
    <div className="studio-workspace">
      <header className="studio-toolbar"><span>CONTENT / {home ? "HOMEPAGE" : "PROJECTS"}</span><div>
        {(project || home) && <span className="studio-save-state">{dirty ? "Unsaved changes" : "Saved"}</span>}
        <button className="studio-button" onClick={reload} disabled={busy}>Reload from disk</button>
        {(project || home) && <button className="studio-button studio-primary" onClick={save} disabled={busy || !dirty}>{busy ? "Working…" : "Save changes"}</button>}
      </div></header>
      <div className="studio-body">
        <div className="studio-heading"><div><p className="studio-eyebrow">{project ? (project.data.published ? "Published project" : "Draft project") : "Portfolio editor"}</p><h1>{title}</h1><p>{project ? `Content/Projects/${project.id}/${project.filename}` : home ? "Set the introduction, featured project and site colors." : "A place to keep your work in order."}</p></div>
          {project ? (project.data.published && <a className="studio-button" href={`/${encodeURIComponent(project.data.slug)}`} target="_blank" rel="noreferrer">View saved page ↗</a>) : !home && <button className="studio-button studio-primary" onClick={newProject} disabled={busy || !state}>+ New project</button>}
        </div>
        {error && <div className="studio-message studio-error" role="alert">{error}</div>}
        {notice && <div className="studio-message" role="status">{notice}</div>}
        {!state && !error && <p role="status">Loading your content…</p>}

        {state && !project && !home && <>
          <div className="studio-list-tools"><Field label="Find a project"><input type="search" placeholder="Search titles or tags" value={query} onChange={(e) => setQuery(e.target.value)} /></Field><p>{state.projects.filter((p) => p.data.published).length} published · {state.projects.filter((p) => !p.data.published).length} drafts</p></div>
          <div className="studio-project-grid">{filtered.map((p) => <button className="studio-project-card" key={p.id} onClick={() => switchTo(`project:${p.id}`)}>
            <div className="studio-card-image"><Thumbnail id={p.id} src={p.data.cover} alt={p.data.coverAlt} /><span className="studio-badge">{p.data.published ? (p.data.slug === state.home.data.centerProject ? "Featured" : "Published") : "Draft"}</span></div>
            <div className="studio-card-copy"><span className="studio-eyebrow">{String(p.data.homeOrder).padStart(2, "0")} / SIZE {p.data.gridSize}</span><h2>{p.data.title}</h2><p>{p.data.tags.join(" · ") || "No tags yet"}</p></div>
          </button>)}</div>{!filtered.length && <div className="studio-empty">No projects match. Try another search or create a project.</div>}
        </>}

        {project && <fieldset className="studio-editor" disabled={busy}>
          <div className="studio-columns"><section className="studio-panel"><h2>Project details</h2><div className="studio-fields">
            <Field label="Project title"><input value={project.data.title} onChange={(e) => changeProject("title", e.target.value)} /></Field>
            <Field label="Page URL" hint={`localhost:3000/${project.data.slug}`}><input value={project.data.slug} onChange={(e) => changeProject("slug", e.target.value)} spellCheck={false} /></Field>
            <Field label="Year"><input type="number" min="1900" max="2200" value={project.data.year} onChange={(e) => changeProject("year", Number(e.target.value))} /></Field>
            <Field label="Homepage order" hint="Smaller numbers appear first in the Index and project navigation."><input type="number" min="0" value={project.data.homeOrder} onChange={(e) => changeProject("homeOrder", Number(e.target.value))} /></Field>
            <Field label="Grid tile size"><select value={project.data.gridSize} onChange={(e) => changeProject("gridSize", e.target.value)}>{["L", "M", "S"].map((size) => <option key={size}>{size}</option>)}</select></Field>
          </div>
          <Field label="Tags" hint="Separate tags with commas."><input value={Array.isArray(project.data.tags) ? project.data.tags.join(", ") : ""} onChange={(e) => changeProject("tags", e.target.value.split(",").map((tag) => tag.trimStart()))} onBlur={() => changeProject("tags", project.data.tags.map((tag) => tag.trim()).filter(Boolean))} /></Field>
          <label className="studio-check"><input type="checkbox" checked={project.data.published} onChange={(e) => changeProject("published", e.target.checked)} /> Published on the portfolio</label>
          <p className="studio-help">Drafts are saved locally and hidden from the portfolio. Add a cover and description before publishing.</p>
          </section>
          <section className="studio-panel"><h2>Homepage cover</h2><div className="studio-cover"><Thumbnail id={project.id} src={project.data.cover} alt={project.data.coverAlt} /></div>
            <Field label="Choose an existing image"><select value={project.data.cover} onChange={(e) => changeProject("cover", e.target.value)}><option value="">Select a cover…</option>{project.assets.filter((asset) => asset.type === "image").map((asset) => <option key={asset.src} value={asset.src}>{asset.name}</option>)}</select></Field>
            <label className="studio-upload">Upload a cover<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={(e) => { void upload(e.target.files, true); e.target.value = ""; }} /></label>
            <Field label="Cover description" hint="A short visual description for accessibility."><input value={project.data.coverAlt} onChange={(e) => changeProject("coverAlt", e.target.value)} /></Field>
          </section></div>
          <section className="studio-panel"><div className="studio-section-heading"><div><h2>Project media <span>{project.data.content.length}</span></h2><p>Ordered from first to last. Move items with the arrows.</p></div><label className="studio-upload">+ Upload images or videos<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,image/avif,video/mp4,video/webm,video/quicktime" onChange={(e) => { void upload(e.target.files); e.target.value = ""; }} /></label></div>
            <div className="studio-add-media"><Field label="Add media already in the project folder"><select value={assetChoice} onChange={(e) => setAssetChoice(e.target.value)}><option value="">Choose a file…</option>{project.assets.map((asset) => <option key={asset.src} value={asset.src}>{asset.name}</option>)}</select></Field><button className="studio-button" disabled={!assetChoice} onClick={() => { const asset = project.assets.find((a) => a.src === assetChoice); if (asset) addAsset(asset); }}>Add to sequence</button></div>
            <p className="studio-help">Uploads save original files immediately (up to 100 MB each). Save changes to update the media sequence. Removing an item keeps its original file.</p>
            {!project.data.content.length && <div className="studio-empty">Your project starts here. Upload a few images or choose existing files above.</div>}
            <div className="studio-media-list">{project.data.content.map((item, index) => <article className="studio-media" key={`${item.src}-${index}`}>
              <div className="studio-media-preview"><Thumbnail id={project.id} src={item.src} type={item.type} alt={item.alt} /><p>{item.src.split("/").pop()}</p></div>
              <div className="studio-media-form"><div className="studio-media-header"><h3>{String(index + 1).padStart(2, "0")} / {item.type}</h3><div><button className="studio-button" disabled={index === 0} aria-label={`Move media ${index + 1} up`} onClick={() => moveMedia(index, -1)}>↑</button><button className="studio-button" disabled={index === project.data.content.length - 1} aria-label={`Move media ${index + 1} down`} onClick={() => moveMedia(index, 1)}>↓</button><button className="studio-button studio-remove" aria-label={`Remove media ${index + 1} from sequence`} onClick={() => changeProject("content", project.data.content.filter((_, i) => i !== index))}>Remove</button></div></div>
                <Field label="Image / video description"><input value={item.alt ?? ""} onChange={(e) => changeMedia(index, "alt", e.target.value)} /></Field>
                <div className="studio-fields"><Field label="Aspect ratio"><select value={item.aspectRatio ?? "Default"} onChange={(e) => changeMedia(index, "aspectRatio", e.target.value)}>{ratios.map((ratio) => <option key={ratio} value={ratio}>{ratio === "Default" ? "Default — original proportions" : ratio}</option>)}</select></Field><Field label="Caption position"><select value={item.captionPosition ?? "bottom"} onChange={(e) => changeMedia(index, "captionPosition", e.target.value)}><option value="bottom">Below image</option><option value="top">Above image</option></select></Field></div>
                {item.type === "video" && <Field label="Video poster (optional)"><select value={item.poster ?? ""} onChange={(e) => changeMedia(index, "poster", e.target.value)}><option value="">No poster</option>{project.assets.filter((a) => a.type === "image").map((a) => <option value={a.src} key={a.src}>{a.name}</option>)}</select></Field>}
                <Field label="Caption label"><input value={item.captionLabel ?? ""} placeholder="01 –" onChange={(e) => changeMedia(index, "captionLabel", e.target.value)} /></Field>
                <Field label="Caption"><textarea rows={4} value={item.caption ?? ""} placeholder="Tell the story behind this image…" onChange={(e) => changeMedia(index, "caption", e.target.value)} /></Field>
              </div>
            </article>)}</div>
          </section>
          <section className="studio-panel"><h2>Project colors</h2><label className="studio-check"><input type="checkbox" checked={project.data.customColors} onChange={(e) => changeProject("customColors", e.target.checked)} /> Use custom colors for this project</label><p className="studio-help">Otherwise, this page inherits the global project colors from Homepage settings.</p>{project.data.customColors && <Colors data={project.data} change={changeProject} />}</section>
        </fieldset>}

        {home && state && <fieldset className="studio-editor" disabled={busy}>
          <section className="studio-panel"><h2>Introduction and navigation</h2><Field label="Introduction"><textarea rows={3} value={home.data.intro} onChange={(e) => changeHome("intro", e.target.value)} /></Field><div className="studio-fields"><Field label="Work button label"><input value={home.data.workLabel} onChange={(e) => changeHome("workLabel", e.target.value)} /></Field><Field label="About button label"><input value={home.data.aboutLabel} onChange={(e) => changeHome("aboutLabel", e.target.value)} /></Field><Field label="Default view"><select value={home.data.defaultView} onChange={(e) => changeHome("defaultView", e.target.value)}><option value="grid">Grid</option><option value="index">Index</option></select></Field><Field label="Center / featured project"><select value={home.data.centerProject} onChange={(e) => changeHome("centerProject", e.target.value)}>{state.projects.filter((p) => p.data.published).map((p) => <option key={p.id} value={p.data.slug}>{p.data.title}</option>)}</select></Field></div></section>
          <section className="studio-panel"><h2>Homepage colors</h2><Colors data={home.data} change={changeHome} /></section>
          <section className="studio-panel"><h2>Global project page colors</h2><p>Applied to every project unless custom colors are enabled on that project.</p><Colors data={home.data} prefix="projectPage" change={changeHome} /></section>
        </fieldset>}
        <footer className="studio-footnote">Changes stay in your local Content folder. Saving keeps a backup of the previous Markdown file.</footer>
      </div>
    </div>
    {creating && <dialog ref={dialogRef} className="studio-modal" aria-labelledby="studio-new-title" onCancel={(event) => { event.preventDefault(); if (!busy) setCreating(false); }}><p className="studio-eyebrow">Something new</p><h2 id="studio-new-title">Create a project</h2><p>Start with a draft. Add images and captions at your own pace.</p>
      {error && <p role="alert" className="studio-error">{error}</p>}
      <form onSubmit={(e) => { e.preventDefault(); void create(); }}><fieldset disabled={busy}><Field label="Project title"><input autoFocus required value={newTitle} onChange={(e) => { setNewTitle(e.target.value); if (!slugEdited) setNewSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} /></Field><Field label="Page URL" hint={`localhost:3000/${newSlug || "your-project"}`}><input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={80} value={newSlug} onChange={(e) => { setNewSlug(e.target.value); setSlugEdited(true); }} /></Field><div className="studio-modal-actions"><button type="button" className="studio-button" onClick={() => { setCreating(false); setError(""); }}>Cancel</button><button className="studio-button studio-primary" type="submit">{busy ? "Creating…" : "Create draft"}</button></div></fieldset></form>
    </dialog>}
  </main>;
}
